
/* File generated by gen_cfile.py. Should not be modified. */

#include "SCU_Frontal.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS16 CAN_Bitrate = 0x3E8;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 Devide_ID[10] = "SCU_F";		/* Mapped at index 0x2004, subindex 0x00 */
UNS8 Suspension_Stroke_Extension = 0x4B;		/* Mapped at index 0x200C, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x24 /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 SCU_Frontal_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 SCU_Frontal_bDeviceNodeId = 0x01;

/**************************************************************************/
/* Array of message processing information */

const UNS8 SCU_Frontal_iam_a_slave = 1;

TIMER_HANDLE SCU_Frontal_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 SCU_Frontal_obj1000 = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1000[] = 
                     {
                       { RO, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 SCU_Frontal_obj1001 = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1001[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 SCU_Frontal_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t SCU_Frontal_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex SCU_Frontal_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&SCU_Frontal_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&SCU_Frontal_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 SCU_Frontal_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 SCU_Frontal_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 SCU_Frontal_obj1008[10] = "";
                    subindex SCU_Frontal_Index1008[] = 
                     {
                       { RO, CANopen_TYPE_visible_string, (void*)&SCU_Frontal_obj1008 }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 SCU_Frontal_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 SCU_Frontal_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 SCU_Frontal_obj1014 = 0x80 + 0x01;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 SCU_Frontal_highestSubIndex_obj1016 = 0;
                    UNS32 SCU_Frontal_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 SCU_Frontal_obj1017 = 0x0;	/* 0 */
                    ODCallback_t SCU_Frontal_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex SCU_Frontal_Index1017[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1018_Vendor_ID = 0x1;	/* 1 */
                    UNS32 SCU_Frontal_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 SCU_Frontal_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 SCU_Frontal_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1018[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1018 },
                       { RO, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1018_Vendor_ID },
                       { RO, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1018_Product_Code },
                       { RO, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1018_Revision_Number },
                       { RO, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x601;	/* 1537 */
                    UNS16 SCU_Frontal_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x581;	/* 1409 */
                    subindex SCU_Frontal_Index1200[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1200 },
                       { RO, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1280_Node_ID_of_the_SDO_Server = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1280[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1280 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1400_COB_ID_used_by_PDO = 0x201;	/* 513 */
                    UNS8 SCU_Frontal_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1400[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1400 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1400_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1400_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1400_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1400_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1400_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1401_COB_ID_used_by_PDO = 0x301;	/* 769 */
                    UNS8 SCU_Frontal_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1401[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1401 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1401_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1401_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1401_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1401_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1401_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1402_COB_ID_used_by_PDO = 0x401;	/* 1025 */
                    UNS8 SCU_Frontal_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1402[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1402 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1402_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1402_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1402_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1402_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1402_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1403_COB_ID_used_by_PDO = 0x501;	/* 1281 */
                    UNS8 SCU_Frontal_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex SCU_Frontal_Index1403[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1403 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1403_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1403_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1403_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1403_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1403_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1600[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1600 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1601[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1601 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1602[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1602 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1603[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1603 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1800_COB_ID_used_by_PDO = 0x181;	/* 385 */
                    UNS8 SCU_Frontal_obj1800_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t SCU_Frontal_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex SCU_Frontal_Index1800[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1800 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1800_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1800_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1800_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1800_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1800_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1801_COB_ID_used_by_PDO = 0x281;	/* 641 */
                    UNS8 SCU_Frontal_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t SCU_Frontal_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex SCU_Frontal_Index1801[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1801 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1801_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1801_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1801_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1801_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1801_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1802_COB_ID_used_by_PDO = 0x381;	/* 897 */
                    UNS8 SCU_Frontal_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t SCU_Frontal_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex SCU_Frontal_Index1802[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1802 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1802_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1802_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1802_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1802_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1802_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS16 SCU_Frontal_obj1803_COB_ID_used_by_PDO = 0x481;	/* 1153 */
                    UNS8 SCU_Frontal_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 SCU_Frontal_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 SCU_Frontal_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t SCU_Frontal_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex SCU_Frontal_Index1803[] = 
                     {
                       { RO, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1803 },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1803_COB_ID_used_by_PDO },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1803_Transmission_Type },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1803_Inhibit_Time },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1803_Compatibility_Entry },
                       { RW, CANopen_TYPE_uint16, (void*)&SCU_Frontal_obj1803_Event_Timer },
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1A00[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1A00[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1A00 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1A01[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1A01[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1A01 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1A02[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1A02 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 SCU_Frontal_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 SCU_Frontal_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex SCU_Frontal_Index1A03[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&SCU_Frontal_highestSubIndex_obj1A03 },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[0] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[1] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[2] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[3] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[4] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[5] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[6] },
                       { RW, CANopen_TYPE_uint32, (void*)&SCU_Frontal_obj1A03[7] }
                     };

/* index 0x2001 :   Mapped variable CAN Bitrate */
                    subindex SCU_Frontal_Index2001[] = 
                     {
                       { RW, CANopen_TYPE_uint16, (void*)&CAN_Bitrate }
                     };

/* index 0x2004 :   Mapped variable Devide ID */
                    subindex SCU_Frontal_Index2004[] = 
                     {
                       { RO, CANopen_TYPE_visible_string, (void*)&Devide_ID }
                     };

/* index 0x200C :   Mapped variable Suspension Stroke Extension */
                    subindex SCU_Frontal_Index200C[] = 
                     {
                       { RW, CANopen_TYPE_uint8, (void*)&Suspension_Stroke_Extension }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const subindex * SCU_Frontal_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	subindex *si= NULL;
	switch(wIndex){
		case 0x1000: si = SCU_Frontal_Index1000; *size= sizeof(SCU_Frontal_Index1000)/sizeof(SCU_Frontal_Index1000[0]); break;
		case 0x1001: si = SCU_Frontal_Index1001; *size= sizeof(SCU_Frontal_Index1001)/sizeof(SCU_Frontal_Index1001[0]); break;
		case 0x1008: si = SCU_Frontal_Index1008; *size= sizeof(SCU_Frontal_Index1008)/sizeof(SCU_Frontal_Index1008[0]); break;
		case 0x1017: si = SCU_Frontal_Index1017; *size= sizeof(SCU_Frontal_Index1017)/sizeof(SCU_Frontal_Index1017[0]); *callbacks = SCU_Frontal_Index1017_callbacks; break;
		case 0x1018: si = SCU_Frontal_Index1018; *size= sizeof(SCU_Frontal_Index1018)/sizeof(SCU_Frontal_Index1018[0]); break;
		case 0x1200: si = SCU_Frontal_Index1200; *size= sizeof(SCU_Frontal_Index1200)/sizeof(SCU_Frontal_Index1200[0]); break;
		case 0x1280: si = SCU_Frontal_Index1280; *size= sizeof(SCU_Frontal_Index1280)/sizeof(SCU_Frontal_Index1280[0]); break;
		case 0x1400: si = SCU_Frontal_Index1400; *size= sizeof(SCU_Frontal_Index1400)/sizeof(SCU_Frontal_Index1400[0]); break;
		case 0x1401: si = SCU_Frontal_Index1401; *size= sizeof(SCU_Frontal_Index1401)/sizeof(SCU_Frontal_Index1401[0]); break;
		case 0x1402: si = SCU_Frontal_Index1402; *size= sizeof(SCU_Frontal_Index1402)/sizeof(SCU_Frontal_Index1402[0]); break;
		case 0x1403: si = SCU_Frontal_Index1403; *size= sizeof(SCU_Frontal_Index1403)/sizeof(SCU_Frontal_Index1403[0]); break;
		case 0x1600: si = SCU_Frontal_Index1600; *size= sizeof(SCU_Frontal_Index1600)/sizeof(SCU_Frontal_Index1600[0]); break;
		case 0x1601: si = SCU_Frontal_Index1601; *size= sizeof(SCU_Frontal_Index1601)/sizeof(SCU_Frontal_Index1601[0]); break;
		case 0x1602: si = SCU_Frontal_Index1602; *size= sizeof(SCU_Frontal_Index1602)/sizeof(SCU_Frontal_Index1602[0]); break;
		case 0x1603: si = SCU_Frontal_Index1603; *size= sizeof(SCU_Frontal_Index1603)/sizeof(SCU_Frontal_Index1603[0]); break;
		case 0x1800: si = SCU_Frontal_Index1800; *size= sizeof(SCU_Frontal_Index1800)/sizeof(SCU_Frontal_Index1800[0]); *callbacks = SCU_Frontal_Index1800_callbacks; break;
		case 0x1801: si = SCU_Frontal_Index1801; *size= sizeof(SCU_Frontal_Index1801)/sizeof(SCU_Frontal_Index1801[0]); *callbacks = SCU_Frontal_Index1801_callbacks; break;
		case 0x1802: si = SCU_Frontal_Index1802; *size= sizeof(SCU_Frontal_Index1802)/sizeof(SCU_Frontal_Index1802[0]); *callbacks = SCU_Frontal_Index1802_callbacks; break;
		case 0x1803: si = SCU_Frontal_Index1803; *size= sizeof(SCU_Frontal_Index1803)/sizeof(SCU_Frontal_Index1803[0]); *callbacks = SCU_Frontal_Index1803_callbacks; break;
		case 0x1A00: si = SCU_Frontal_Index1A00; *size= sizeof(SCU_Frontal_Index1A00)/sizeof(SCU_Frontal_Index1A00[0]); break;
		case 0x1A01: si = SCU_Frontal_Index1A01; *size= sizeof(SCU_Frontal_Index1A01)/sizeof(SCU_Frontal_Index1A01[0]); break;
		case 0x1A02: si = SCU_Frontal_Index1A02; *size= sizeof(SCU_Frontal_Index1A02)/sizeof(SCU_Frontal_Index1A02[0]); break;
		case 0x1A03: si = SCU_Frontal_Index1A03; *size= sizeof(SCU_Frontal_Index1A03)/sizeof(SCU_Frontal_Index1A03[0]); break;
		case 0x2001: si = SCU_Frontal_Index2001; *size= sizeof(SCU_Frontal_Index2001)/sizeof(SCU_Frontal_Index2001[0]); break;
		case 0x2004: si = SCU_Frontal_Index2004; *size= sizeof(SCU_Frontal_Index2004)/sizeof(SCU_Frontal_Index2004[0]); break;
		case 0x200C: si = SCU_Frontal_Index200C; *size= sizeof(SCU_Frontal_Index200C)/sizeof(SCU_Frontal_Index200C[0]); break;
		default:
			return NULL;
	}
	return si;
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status SCU_Frontal_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

CO_Data SCU_Frontal_Data = CANOPEN_NODE_DATA_INITIALIZER(SCU_Frontal);

UNS8 ObjDict_DataSize(const subindex *s) {
  if(s->bDataType==valueRange_EMC) return 1;
  else return 0;
}

