
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SCU_FRONTAL_H
#define SCU_FRONTAL_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 SCU_Frontal_valueRangeTest (UNS8 typeValue, void * value);
const subindex * SCU_Frontal_scanIndexOD (UNS16 wIndex, UNS8 *size, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data SCU_Frontal_Data;
extern UNS16 CAN_Bitrate;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 Devide_ID[10];		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 Suspension_Stroke_Extension;		/* Mapped at index 0x200C, subindex 0x00*/

#endif // SCU_FRONTAL_H
